# Generated by Django 4.1 on 2023-03-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=100)),
                ('contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ')], max_length=3)),
                ('data_admissao', models.DateField()),
                ('email_constitucional', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('matricula_gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferias.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mensagem', models.CharField(max_length=200)),
                ('data_envio', models.DateField()),
                ('visto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recusado', 'Recusado'), ('aprovado', 'Aprovado')], max_length=8)),
                ('data_criacao', models.DateField()),
                ('antecipacao_salario', models.BooleanField()),
                ('matricula_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.funcionario')),
                ('notificacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.notificacao')),
            ],
        ),
    ]
